# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SBA\github\pyqt5_example\stopwatch.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(210, 170, 75, 23))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(Form)
        self.btn2.setGeometry(QtCore.QRect(340, 170, 75, 23))
        self.btn2.setObjectName("btn2")
        self.label1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(22)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn1.setText(_translate("Form", "Start"))
        self.btn2.setText(_translate("Form", "Stop"))
        self.label1.setText(_translate("Form", "00.00.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
